version: '{build}'

environment:
  GITHUB_TOKEN:
    secure: 4vpPlabt2OKA/pyJKSZUr3KJg8y0uJFnzf/kTmVUTCPIb9Q3fpjED+1LEXHYQ4UY
  SCM_USERNAME:
    secure: 8BjoFIdSfcFM5UNtivbS5w==
  APPVEYOR_RDP_PASSWORD:
    secure: 4amxfxphFUcpp60d9Q6gJg==

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - cinst jdk8

branches:

  only:

  - master

only_commits:

  message: /\[maven-release-plugin\] prepare release/

build_script:

- ps: >-
    refreshenv

    java -version

    echo %JAVA_HOME%

    $ENV:PATH=”$ENV:PATH;$ENV:WIX\bin”

    $ENV:BINJR_BUILD_NUMBER=$ENV:APPVEYOR_BUILD_NUMBER

    git clone -b travis https://github.com/fthevenet/binjr.git ".\binjr\target\travis"

    cd binjr

    mvn clean deploy --settings "./target/travis/settings.xml" -P buildNativeBundles
