version: '{build}'

environment:
  GITHUB_TOKEN:
    secure: 4vpPlabt2OKA/pyJKSZUr3KJg8y0uJFnzf/kTmVUTCPIb9Q3fpjED+1LEXHYQ4UY
  SCM_USERNAME:
    secure: 8BjoFIdSfcFM5UNtivbS5w==
  APPVEYOR_RDP_PASSWORD:
    secure: 4amxfxphFUcpp60d9Q6gJg==

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


install:
  - cinst jdk8  -params 'installdir=C:\\latest_jdk8'
  - SET JAVA_HOME=C:\latest_jdk8
  - SET PATH=C:\latest_jdk8\bin;%PATH%

branches:

  only:

  - binjr-1_x

only_commits:

  message: /\[maven-release-plugin\] prepare release/

build_script:

- ps: >-

    $ENV:PATH=”$ENV:PATH;$ENV:WIX\bin”

    $ENV:BINJR_BUILD_NUMBER=$ENV:APPVEYOR_BUILD_NUMBER

    cd binjr

    mvn clean deploy --settings "./cd/maven_settings.xml" -P buildNativeBundles
