version: '{build}'

environment:
  GITHUB_TOKEN:
    secure: 4vpPlabt2OKA/pyJKSZUr3KJg8y0uJFnzf/kTmVUTCPIb9Q3fpjED+1LEXHYQ4UY
  SCM_USERNAME:
    secure: 8BjoFIdSfcFM5UNtivbS5w==
  APPVEYOR_RDP_PASSWORD:
    secure: 4amxfxphFUcpp60d9Q6gJg==

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


install:
  - choco install openjdk
  - SET PATH=%JAVA_HOME%\bin;%PATH%

branches:

  only:

  - binjr2

build_script:

- ps: >-

    $ENV:PATH=”$ENV:PATH;$ENV:WIX\bin”

    $ENV:BINJR_BUILD_NUMBER=$ENV:APPVEYOR_BUILD_NUMBER

    cd binjr

    mvn clean deploy  --settings "./cd/maven_settings.xml" -P binjr-snapshot,build-native-bundle,bundle-windows
